### ISSUE TITLE
Review version segments 

### ISSUE THREAD

**Issue by ignasi35** [asyncapi/topic-definition#1]
According to the docs:

> Message version
> 
> The version of the message for the given service. We use a variation of semantic versioning, with only the major and minor numbers. This way, a service can safely listen/publish to all X.* versions because the message format does not contain any breaking changes.
> 
> Example:
> 
> hitch.accounts.1.0.event.user.signup
> 
> Note: This version number is NOT related to your service or program version.

I think this is too granular and also introduces a few problems:

1. a service publishing `EventA` may need to evolve the for mat of that event. The change may or may not backwards compatible. If it is backwards compatible then the change could update the MINOR (that is actually alllowed in [semver](http://semver.org/)). The proposal, as it is, would require the creation of a new topic even though the consumers would be compatible.
2. with such a high granularity, a single message will have to be serialized in too many topics every time it's emitted. The only solution to take down this overhead is to have a clear list of consumers for any given version of the topic.

Considering the versioning suggested in this topic name is not related to the service where the message is publish I think the topic definition could be implemented with a single number that is only increased when there's a breaking change: `hitch.accounts.1.event.user.signup`

**Comment by fmvilas** [comment]
Totally agree. Would you mind to open a PR with such changes?
