### ISSUE TITLE
Replace [action] with [command]

### ISSUE THREAD

**Issue by ignasi35** [asyncapi/topic-definition#2]
This definition suggests categorizing messages between `events` and `actions`.

I think the distiction is very natural but the industry is leaning towards `events` vs `commands`. These names come from patterns like Event Sourcing, Command Sourcing and CQRS where a command is a message requesting a state-change and an event is a message notifying of the state being changed.

**Comment by fmvilas** [comment]
Agree. That should be changed.

**Comment by fmvilas** [comment]
I just added this change. Thanks for the suggestion!
